version: '3.3'

services:
  chat_api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    container_name: chat_api
    expose:
      - 8090
    ports:
      - 8090:8090
    volumes:
      - ./server:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: bash -c "gunicorn --bind 0.0.0.0:8090 --workers 4 --worker-class uvicorn.workers.UvicornWorker src.api.application:api"

  chat_client:
    container_name: chat_client
    build:
      dockerfile: Dockerfile
      context: "./client"
    ports:
     - 3002:3000
    volumes:
      - ./client:/app
    tty: true
    stdin_open: true
    depends_on:
      - chat_api
    command: npm start


