version: '3.3'

services:
  chat_api:
    restart:
      always
    build:
      dockerfile: Dockerfile
      context: "./server"
    container_name: chat_api
    expose:
      - 8090
    ports:
      - 8090:8090
    volumes:
      - ./server:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: bash -c "uvicorn src.api.application:api --reload --host 0.0.0.0 --port 8090"

  chat_client:
    container_name: chat_client
    build:
      dockerfile: Dockerfile
      context: "./client"
    ports:
     - 3002:3000
    volumes:
      - ./client:/app
    tty: true
    stdin_open: true
    depends_on:
      - chat_api
    command: npm start


