version: '3.3'

services:
  chat_api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    container_name: chat_api
    expose:
      - 8090
    ports:
      - 8090:8090
    volumes:
      - ./server:/app
    environment:
      - DATABASE_URL=postgresql://pop_user:pop_user@pop_db:5432/pop_postgres
      - AUTH_SECRET=s3cr3t
      - AUTH_ALGORITHM=HS256
      - AUTH_TOKEN_TTL=86400
    command: bash -c "gunicorn --bind 0.0.0.0:8090 --workers 4 --worker-class uvicorn.workers.UvicornWorker main:app"

  chat_client:
    container_name: chat_client
    build:
      dockerfile: Dockerfile
      context: "./client"
    ports:
     - 3002:3000
    volumes:
      - ./client:/app
    tty: true
    stdin_open: true
    depends_on:
      - chat_api
    command: npm start


